### ISSUE TITLE
Repaint on containing CssLayout stops the poller

### ISSUE THREAD

**Issue by jouni** [wolfie/Refresher#1]
When the Refresher is contained inside a CssLayout, the polling is canceled after a repaint is done for the parent layout. The VCssLayout first removes all components from it and then repaints them.

I suspect there's either some logic error in the onDetach/onAttach methods on VRefresher, or then GWT works in some mysterious ways that are unpredictable.

When using a VerticalLayout everything works as expected.

Workaround is to call Refresher.setRefreshInterval the same time the parent CssLayout is repainted.

**Test case:**

```
public class RefresherTest extends Application {

    Refresher r = new Refresher();

    @Override
    public void init() {

        final Layout l = new CssLayout();
        final Window main = new Window("RefresherTest", l);
        setMainWindow(main);

        l.addComponent(r);
        l.addComponent(new Label("Testing"));

        r.setRefreshInterval(1000);

        main.addComponent(new Button("Repaint layout",
                new Button.ClickListener() {
                    public void buttonClick(ClickEvent event) {
                        l.requestRepaint();
                    }
                }));

    }

}
```

**Comment by wolfie** [comment]
This should be fixed now
