### ISSUE TITLE
Vaadin7: widget not found

### ISSUE THREAD

**Issue by archiecobbs** [wolfie/Refresher#3]
I'm using Refresher in 7.0.0.beta5 (commit 93f3c9899b) and am able to compile it successfully, but get this message on the screen when trying to use it:

Widgetset does not contain implementation for com.github.wolfie.refresher.Refresher. Check its component connector's @Connect mapping, widgetsets GWT module description file and re-compile your widgetset. In case you have downloaded a vaadin add-on package, you might want to refer to add-on instructions.

Any ideas?

**Comment by wolfie** [comment]
As the commit message says, I'm having troubles with it too. So I don't
really know. Maybe I have some time to work with it on Friday. I might
convert it into an extension anyways. I thought Leif Åstrand had already
one released in the directory, but i couldn't find it right now.

On Fri, Oct 19, 2012 at 12:27 AM, Archie L. Cobbs
notifications@github.comwrote:

> I'm using Refresher in 7.0.0.beta5 (commit 93f3c98https://github.com/wolfie/Refresher/commit/93f3c9899b)
> and am able to compile it successfully, but get this message on the screen
> when trying to use it:
> 
> Widgetset does not contain implementation for
> com.github.wolfie.refresher.Refresher. Check its component connector's
> @Connect https://github.com/Connect mapping, widgetsets GWT module
> description file and re-compile your widgetset. In case you have downloaded
> a vaadin add-on package, you might want to refer to add-on instructions.
> 
> Any ideas?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wolfie/Refresher/issues/3.

## 

Henrik Paul

**Comment by wolfie** [comment]
fixed in 5148e78971429c28ea56c168ec7bc6ba2267e080

**Comment by archiecobbs** [comment]
Works great, thanks!

**Comment by sockeqwe** [comment]
Hi, I have developed a Vaadin 6 Addon that uses your Refresher Addon. No I try to migrate this Addon to Vaadin 7.
I wrote a simple Vaadin 7 Application to test  my Addon, but when I try to run my demo application i get the following error message:

Widgetset does not contain implementation for com.github.wolfie.refresher.Refresher. Check its component connector's @Connect mapping, widgetsets GWT module description file and re-compile your widgetset. In case you have downloaded a vaadin add-on package, you might want to refer to add-on instructions.

I tried to annotated my main UI class with @Widgetset("com.github.wolfie.refresher.RefresherWidgetset")
and recompile the widget set, but now I see an empty screen with the error log on my tomcat server:

Apr 21, 2013 8:29:06 PM com.vaadin.server.VaadinServlet serveStaticResourcesInVAADIN
INFO: Requested resource [/VAADIN/widgetsets/com.github.wolfie.refresher.RefresherWidgetset/com.github.wolfie.refresher.RefresherWidgetset.nocache.js] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder.

Any idea what could be wrong or how to fix that?

**Comment by wolfie** [comment]
Your application should not configure itself to use Refresher's widgetset, since it doesn't really contain a widgetset, only metadata for a widgetset containing Refresher. Your application needs to compile its own widgetset. More information can be found at https://vaadin.com/book/-/page/gwt.eclipse.html and https://vaadin.com/book/-/page/clientside.compiling.html

**Comment by sockeqwe** [comment]
Thank you for your answer. My Problem is:
I wrote a Model-View-Presenter Addon (https://github.com/sockeqwe/Vaadin-MVP-Lite), so my addon provides just some simple skeleton classes for architecture, no client side widgets. But this addon provides an EventBus, that is shared by every user to realize some kind of realtime communication. Thats where I use your Refresher addon to poll/query periodically the EventBus for new events.

So I wrote a simple demo app (https://github.com/sockeqwe/Vaadin-MVP-Lite-MailExample), that have dependencies to your Refresher Addon and to my Model-View-Presenter Addon. Everything worked as expected with Vaadin 6. Now I try to migrate that to Vaadin 7. When I do UI.addExtension(new Refresher()) I get this error Message: 

Widgetset does not contain implementation for com.github.wolfie.refresher.Refresher. Check its component connector's @Connect mapping, widgetsets GWT module description file and re-compile your widgetset. In case you have downloaded a vaadin add-on package, you might want to refer to add-on instructions.

Any idea?

**Comment by wolfie** [comment]
Please, write these kinds of messages in the Refresher's thread:
https://vaadin.com/forum#!/thread/77100 - GitHub Issues isn't a place for
discussion.

On Mon, Apr 22, 2013 at 2:40 PM, sockeqwe notifications@github.com wrote:

> Thank you for your answer. My Problem is:
> I wrote a Model-View-Presenter Addon (
> https://github.com/sockeqwe/Vaadin-MVP-Lite), so my addon provides just
> some simple skeleton classes for architecture, no client side widgets. But
> this addon provides an EventBus, that is shared by every user to realize
> some kind of realtime communication. Thats where I use your Refresher addon
> to poll/query periodically the EventBus for new events.
> 
> So I wrote a simple demo app, that have dependencies to your Refresher
> Addon and to my Model-View-Presenter Addon. Everything worked as expected
> with Vaadin 6. Now I try to migrate that to Vaadin 7. When I do
> UI.addExtension(new Refresher()) I get this error Message:
> 
> Widgetset does not contain implementation for
> com.github.wolfie.refresher.Refresher. Check its component connector's
> @Connect https://github.com/Connect mapping, widgetsets GWT module
> description file and re-compile your widgetset. In case you have downloaded
> a vaadin add-on package, you might want to refer to add-on instructions.
> 
> Any idea?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wolfie/Refresher/issues/3#issuecomment-16779549
> .

## 

Henrik Paul
