### ISSUE TITLE
Please update for Vaadin 7.0.0.beta11

### ISSUE THREAD

**Issue by archiecobbs** [wolfie/Refresher#4]
I get this error with Vaadin 7.0.0.beta11 when compiling:

[ERROR] Line 11: The type RefresherConnector must implement the inherited abstract method AbstractExtensionConnector.extend(ServerConnector)

**Comment by wolfie** [comment]
I'll probably do a round of fix-ups on my add-ons once the RC is out.

**Comment by aanno** [comment]
+1
For the moment, I've done a (friendly) fork to fix refresher for beta11. See my pull request.

**Comment by wolfie** [comment]
Fixed.

I saw the pull request. Decided to fix it myself, since pull request converted the project into Maven instead. See 097ca64bbfbc73035b65c04e1b6492662dabd62d for resolution
